# Site settings
title: Code's Cool Dallas
description: > # this means to ignore newlines until "baseurl:"
  Hands on workshops: node.js, javascript and beyond
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://codescooldallas.github.io" # the base hostname & protocol for your site
twitter_username: codescooldal

# Publish future posts
future: true

# Build settings
markdown: kramdown

# Github Flavored Markdown
kramdown:
  input: GFM
  hard_wrap: false

include: [
  "_sass"
]

libs:
  jquery: "lib/jquery-2.2.0.min.js"
  moment: "lib/moment-2.11.1.min.js"
  bootstrap: "lib/bootstrap-sass-3.3.6/assets"

plugins:
  - jekyll-coffeescript

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "page"
